apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poc.fullname" . }}-frontend
  labels:
    app: {{ include "poc.fullname" . }}
    component: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ include "poc.fullname" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "poc.fullname" . }}
        component: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: curlimages/curl:8.2.1
          command:
            - sh
            - -c
            - |
              until curl -sS --max-time 2 http://backend:{{ .Values.service.backend.port }} >/dev/null 2>&1; do
                echo "waiting for backend...";
                sleep 1;
              done
      containers:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontend.port }}
