apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poc.fullname" . }}-backend
  labels:
    app: {{ include "poc.fullname" . }}
    component: backend
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: {{ include "poc.fullname" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "poc.fullname" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          env:
          {{- range $key, $val := .Values.backend.env }}
            - name: {{ $key }}
              value: {{ quote $val }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.backend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
