{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "poc.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "poc.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.service.frontend.port }}
          {{- end }}
    {{- end }}
{{- end -}}
