apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc.fullname" . }}-keycloak
  labels:
    app: {{ include "poc.fullname" . }}
    component: keycloak
spec:
  type: {{ .Values.service.keycloak.type }}
  ports:
    - port: {{ .Values.service.keycloak.port }}
      targetPort: {{ .Values.service.keycloak.port }}
      protocol: TCP
      name: http
      {{- if eq .Values.service.keycloak.type "NodePort" }}
      nodePort: {{ .Values.service.keycloak.nodePort }}
      {{- end }}
  selector:
    app: {{ include "poc.fullname" . }}
    component: keycloak
