apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-backend
  template:
    metadata:
      labels:
        app: sample-backend
    spec:
      containers:
        - name: backend
          image: k8-sample-backend:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI
              value: http://localhost:30081/realms/demo/protocol/openid-connect/auth
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI
              value: http://keycloak:8080/realms/demo/protocol/openid-connect/token
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI
              value: http://keycloak:8080/realms/demo/protocol/openid-connect/userinfo
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI
              value: http://keycloak:8080/realms/demo/protocol/openid-connect/certs
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  # type: ClusterIP
  type: NodePort
  selector:
    app: sample-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
