apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-frontend
  template:
    metadata:
      labels:
        app: sample-frontend
    spec:
      containers:
        - name: frontend
          image: k8-sample-frontend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  # type: ClusterIP
  type: NodePort
  selector:
    app: sample-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
