server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: sample-backend
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: sample-app
            client-secret: sample-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: http://localhost:8081/realms/demo/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/demo/protocol/openid-connect/certs
            user-name-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: health,info
